name: Go Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:

  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.1

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v -o ftp2go.exe ./...

    - name: Run go vet
      run: go vet ./...

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ftp2go.exe
        path: ftp2go.exe