name: Go Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  GOVERSION: 1.24.3

jobs:
  matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        output: [ftp2go, ftp2go.exe]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GOVERSION }}

    - name: Build
      run: |
        go mod verify
        go build -v -o ${{ matrix.output }} ./...
        go vet ./...
 
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.output }}