name: Go Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  GOVERSION: 1.24.3

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GOVERSION }}

    - name: Build
      run: |
        go mod verify
        go build -v -o ftp2go ./...
        go vet ./...

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ftp2go
        path: ftp2go

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GOVERSION }}

    - name: Build
      run: |
        go mod verify
        go build -v -o ftp2go.exe ./...
        go vet ./...

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ftp2go.exe
        path: ftp2go.exe
